const fs = require('fs');
const path = require('path');

const missing = require('./missing_dictionary.json');

const PROMPTS = {
  // City
  city_building: "A charming multi-story claymorphic stone city building with neat glass windows and red roof",
  city_shop: "A cute neighborhood grocery shop boutique with striped fabric awning and display window",
  city_market: "A lively oriental bazaar canopy stall with wicker baskets of fresh fruits and nuts",
  city_school: "A friendly schoolhouse building with entrance steps, bell tower, and clock",
  city_hospital: "A clean modern hospital clinic building with ambulance cross sign",
  city_park: "A peaceful green city park with wooden bench, leafy green tree, and vintage lamppost",
  city_square: "A sunny town square plaza with stone paving and a decorative stone fountain",
  city_bridge: "An arched stone bridge over a clear rushing mountain stream",
  city_road: "A smooth asphalt road highway winding through green hills with dashed lines",
  city_railway: "Toy train railroad tracks with wooden ties and a railway signal sign",
  city_airport: "A modern airport passenger terminal with a cute white airplane on the runway",
  city_port: "A peaceful harbor dock with wooden pier, small boat, and cute lighthouse",
  city_fountain: "An elegant round stone water fountain with sparkling water splashing",
  city_monument: "A majestic ancient Caucasian stone watchtower memorial monument",
  city_museum: "A classical museum building with grand stone columns and entrance steps",
  city_theatre: "A grand theater building with entrance columns and red theater curtains",
  city_cinema: "A movie theater facade with box office, red cinema chairs, and popcorn bucket",
  city_bank: "A solid bank building with columns, safe vault door, and golden coin",
  city_hotel: "A welcoming boutique hotel building with entrance awning and luggage trolley",
  city_restaurant: "A cozy Caucasian family cafe restaurant with outdoor dining table and teapot",
  city_cafe: "A charming sidewalk cafe with coffee cup sign and outdoor umbrella table",
  city_pharmacy: "An apothecary pharmacy storefront with green medical crescent cross sign",
  city_police: "A police station building with blue star emblem and police patrol car",
  city_firestation: "A red brick fire station building with garage door and red fire engine truck",
  city_mosque: "A magnificent white stone mosque with elegant minarets and glowing golden dome",
  city_kindergarten: "A bright colorful cheerful kindergarten building with playground slide",
  city_playground: "A children playground with bright red slide, swing set, and sandpit",
  city_post: "A post office building with blue postal horn sign and yellow mailbox",
  city_crosswalk: "A clean pedestrian zebra crosswalk on road with blue walking sign",
  city_lantern: "A vintage cast iron street lamp glowing with warm golden evening light",
  city_bench: "A comfortable wooden park bench with wrought iron sides under a leafy tree",
  city_bakery: "An artisan bakery shop storefront with golden baked bread loaves in window",
  city_zoo: "A friendly zoo entrance gateway arch with cute cartoon animal figures",
  city_library: "A quiet library building with tall arched windows and bookshelves",
  city_stadium: "A sports arena stadium with green football field pitch and stadium floodlights",

  // House
  house_room: "A cozy tidy children bedroom with soft bed, rug, and sunny window",
  house_kitchen: "A clean modern kitchen with countertop, wooden cabinets, and dining table",
  house_bedroom: "A peaceful cozy bedroom with comfortable bed, fluffy pillows, and bedside lamp",
  house_bathroom: "A sparkling clean bathroom with white bathtub, mirror, and soft towels",
  house_living: "A warm living room with comfortable couch sofa, coffee table, and carpet",
  house_table: "A sturdy wooden dining table with smooth polished surface",
  house_chair: "A comfortable wooden dining chair with curved backrest",
  house_bed: "A cozy wooden bed with soft mattress, fluffy white duvet, and blue pillow",
  house_sofa: "A plush comfortable living room sofa couch with soft cushions",
  house_wardrobe: "A tall wooden clothes wardrobe closet with two doors and brass handles",
  house_shelf: "A wooden wall bookshelf with colorful neat books standing upright",
  house_tv: "A modern flat screen television monitor on a sleek media stand",
  house_fridge: "A modern kitchen refrigerator fridge with freezer door and fresh magnets",
  house_microwave: "A compact kitchen microwave oven with digital display and glass door",
  house_washing: "A modern front-loading laundry washing machine with round glass door",
  house_vacuum: "A modern canister vacuum cleaner with hose and nozzle brush",
  house_door: "A solid wooden front entrance door with brass doorknob and keyhole",
  house_window: "A clean glass window with white wooden frame and open curtains",
  house_roof: "A classic house roof with neat red clay tiles and chimney",
  house_floor: "A warm polished parquet wooden floor surface with wood grain pattern",
  house_wall: "A neat pastel painted house interior wall with a small framed picture",
  house_garden: "A blooming garden with green grass, colorful flowerbeds, and fruit tree",
  house_fence: "A neat white picket wooden garden fence with green grass",
  house_gate: "An ornate wrought iron garden gate opening onto a stone path",
  house_curtain: "Soft fabric window curtains tied back with golden ribbon cords",
  house_lamp: "A stylish bedside table lamp with fabric shade glowing warmly",
  house_stairs: "A wooden indoor staircase steps with smooth handrail railing",
  house_ceiling: "A clean smooth room ceiling with an elegant hanging pendant chandelier light",
  house_attic: "A cozy wooden attic loft room under the roof with round gable window",
  house_chimney: "A brick house chimney on roof with gentle smoke puff",
  house_stove: "A traditional warm brick cooking stove oven with crackling firewood",
  house_lock: "A sturdy brass padlock with shiny golden key inserted",
  house_handle: "An elegant polished brass lever door handle mounted on wood",
  house_tap: "A shiny chrome water sink faucet tap with flowing crystal water drop",
  house_trash: "A neat green pedal waste bin with closed lid",
  house_iron: "A modern steam clothes iron with smooth ceramic soleplate",

  // Shopping
  shop_store: "A cute neighborhood retail store with display counter and shopping baskets",
  shop_market: "An open market stall with crates of ripe vegetables and fruits",
  shop_supermarket: "A modern supermarket grocery aisle with stocked shelves and cart",
  shop_pharmacy: "An apothecary pharmacy counter with medicine bottles and green cross",
  shop_bookshop: "A charming bookshop storefront with stacked picture books in window",
  shop_bread: "A crusty round golden baked hearth bread loaf with wheat grain ear",
  shop_milk: "A glass milk bottle with white milk and blue cap next to a glass cup",
  shop_meat: "Fresh cuts of halal beef steak on butcher butcher board with rosemary",
  shop_fish: "A fresh silver trout fish lying on crushed ice",
  shop_eggs: "A cardboard carton tray filled with six fresh brown chicken eggs",
  shop_fruit: "A woven wicker fruit basket overflowing with apples, oranges, and bananas",
  shop_veg: "A wooden crate of fresh garden vegetables: carrots, tomatoes, and cucumbers",
  shop_sugar: "A vintage glass sugar dispenser bowl filled with white crystalline sugar",
  shop_salt: "A ceramic salt shaker cellar with pinch of pure white table salt",
  shop_oil: "A glass bottle of golden extra virgin olive cooking oil with olive branch",
  shop_juice: "A tall glass pitcher filled with fresh orange juice with citrus slice",
  shop_water: "A clear glass bottle of pure mountain spring drinking water with droplets",
  shop_buy: "A smiling customer placing groceries into a shopping basket",
  shop_sell: "A friendly shopkeeper handing a paper grocery bag across the checkout counter",
  shop_pay: "A customer tapping contactless payment card on modern payment terminal",
  shop_price: "A yellow discount price tag label with golden ribbon cord",
  shop_money: "Neat stacks of paper banknote bills and a pile of shiny gold coins",
  shop_change: "A neat collection of shiny silver and bronze coins in a palm",
  shop_basket: "A bright red plastic supermarket shopping basket with wire handles",
  shop_list: "A neat paper grocery shopping checklist with checked checkboxes and pencil",
  shop_cart: "A shiny metal wire supermarket shopping grocery cart trolley with red handle",
  shop_bag: "An eco-friendly brown kraft paper grocery bag with handles and fresh produce",
  shop_scales: "A vintage brass balance weight scale with counterweights",
  shop_coins: "A sparkling scattered pile of shiny golden and bronze currency coins",
  shop_bankcard: "A modern blue debit bank card with gold EMV smart chip",
  shop_receipt: "A paper store purchase receipt printed paper slip",
  shop_cheap: "A green discount sale badge label with checkmark",
  shop_expensive: "A sparkling luxury golden diamond gemstone inside velvet box",

  // Health
  health_hand: "A clean healthy human hand palm with fingers spread friendly",
  health_leg: "A sporty healthy leg wearing comfortable athletic sneaker shoe",
  health_head: "A cute friendly cartoon character head with cheerful smiling expression",
  health_eye: "A bright clear healthy sparkling brown human eye with eyelashes",
  health_ear: "A clean cute human ear with earring or listening waves",
  health_nose: "A cute smiling human nose profile",
  health_mouth: "A cheerful smiling mouth with clean white teeth and pink lips",
  health_tooth: "A sparkling clean white tooth character holding a toothbrush",
  health_heart: "A vibrant healthy anatomical red heart with golden glowing pulse",
  health_pain: "A small red band-aid adhesive plaster with a soothing green leaf",
  health_flu: "A cute box of soft facial paper tissues next to hot cup of lemon tea",
  health_fever: "A clinical thermometer showing elevated temperature next to ice pack",
  health_cough: "A natural herbal cough syrup bottle with medicinal spoon",
  health_headache: "A soothing cooling gel pack compress on forehead with soft towel",
  health_doctor: "A kind doctor wearing white lab coat and blue stethoscope",
  health_nurse: "A gentle healthcare nurse with medical uniform and clipboard",
  health_medicine: "Glass medicine bottle with dropper and colorful capsules",
  health_hospital: "A modern medical hospital building with emergency entrance",
  health_ambulance: "A white emergency ambulance van vehicle with red siren lights",
  health_pharmacy: "A pharmacy store counter with mortar and pestle and vitamins",
  health_sport: "Athletic running shoes with a water bottle and jump rope",
  health_food: "A healthy balanced food plate with fresh salad, grilled chicken, and avocado",
  health_water: "A tall clear glass filled with pure mineral water with splash",
  health_rest: "A comfortable hammock hanging between two leafy trees in gentle breeze",
  health_clean: "A sparkling clean bathroom sink with bar of soap and white bubbles",
  health_soap: "A bar of fragrant pastel soap sitting on a ceramic dish with suds",
  health_toothbrush: "A colorful children toothbrush with swirl of fresh toothpaste",
  health_wound: "A gentle adhesive band-aid plaster strip with heart emblem",
  health_bandage: "A roll of white medical cotton gauze bandage roll",
  health_thermometer: "A digital medical body thermometer showing normal 36.6 reading",
  health_vitamins: "A bottle of chewable children multivitamin gummies in fruit shapes",
  health_sleep: "A cute moon sleeping peacefully on a fluffy white cloud wearing nightcap",
  health_healthy: "A strong energetic cheerful cartoon boy flexing biceps with big smile",

  // Sport
  sport_run: "A pair of fast athletic running shoes leaving colorful motion speed streaks",
  sport_swim: "Swimming goggles, silicone cap, and clear blue water ripples",
  sport_football: "A classic black and white stitched soccer football ball on green turf",
  sport_volleyball: "A colorful yellow and blue volleyball ball hovering over the net",
  sport_basketball: "A textured orange basketball ball swishing into a net hoop",
  sport_tennis: "A tennis racket with a bright neon yellow tennis ball",
  sport_boxing: "A pair of shiny red leather boxing gloves tied with white laces",
  sport_wrestling: "A traditional wrestling singlet with championship wrestler belt on mat",
  sport_gymnastics: "Wooden gymnastic balance rings hanging from straps",
  sport_ski: "A pair of downhill skis with ski poles on sparkling fresh snow",
  sport_cycle: "A modern road sports bicycle with lightweight frame and helmet",
  sport_ball: "A colorful collection of sports balls: soccer, basketball, tennis, volleyball",
  sport_gate: "A football soccer goal net with white painted posts on grass",
  sport_bat: "A wooden baseball bat resting next to a white baseball ball",
  sport_play: "Two cheerful children kicking a soccer ball together on green field",
  sport_win: "A triumphant champion podium with big shiny golden number 1 trophy",
  sport_lose: "A polite handshake between two young sports opponents showing sportsmanship",
  sport_team: "A group of cheerful young teammates in matching sports jerseys huddled together",
  sport_train: "An exercise gym set with dumbbell weights, jump rope, and water bottle",
  sport_stadium: "A grand outdoor stadium arena with bright floodlights and running track",
  sport_medal: "A shiny golden winner first-place medal with red ribbon lanyard",
  sport_cup: "A glorious tall golden championship trophy cup with two curved handles",
  sport_whistle: "A shiny chrome sports referee whistle on a braided neck lanyard",
  sport_jump: "Athletic track high jump crossbar with landing safety mattress",
  sport_judo: "A crisp white judogi martial arts uniform folded with black belt",
  sport_skates: "A pair of shiny white figure ice skates with sharp steel blades",
  sport_boxing_gloves: "Red boxing sparring gloves resting on the edge of a boxing ring",
  sport_coach: "A sports trainer coach holding a tactical chalkboard clipboard and whistle",

  // Toys
  toy_doll: "A sweet handcrafted rag doll in modest floral dress with button eyes",
  toy_ball: "A bouncy rubber toy ball with bright colorful swirling stripes",
  toy_car: "A cute red wooden toy sports car with rolling wooden wheels",
  toy_bear: "A soft fluffy brown plush teddy bear with a warm smile and bow tie",
  toy_blocks: "A colorful wooden building blocks castle tower with ABC letters",
  toy_puzzle: "A colorful jigsaw puzzle with interlocking wooden pieces fitting together",
  toy_robot: "A friendly retro metal toy robot with antenna and winding key",
  toy_plane: "A cute wooden toy airplane with propeller and wheels",
  toy_train: "A colorful wooden toy locomotive steam train with two carriages on tracks",
  toy_soldier: "A classic toy tin soldier standing at attention in parade uniform",
  toy_sword: "A traditional handcrafted wooden toy sword with rounded safety tip",
  toy_gun: "A colorful plastic toy pop dart blaster with soft foam suction dart",
  toy_play: "A playroom corner with scattered colorful toys and plush animals",
  toy_hide: "A playful child peek-a-boo smiling from behind a soft armchair",
  toy_seek: "A cheerful child playfully searching with a toy magnifying glass",
  toy_run: "A cheerful toddler running happily across green lawn with open arms",
  toy_jump: "A child jumping happily on a bouncy outdoor garden trampoline",
  toy_drum: "A colorful toy marching drum with wooden drumsticks",
  toy_kite: "A bright diamond-shaped flying kite soaring in blue sky with ribbon tail",
  toy_swing: "A wooden garden tree swing swaying gently on rope ropes",
  toy_slide: "A bright curved children playground slide with ladder steps",
  toy_top: "A colorful spinning top toy whirling with motion blur rings",
  toy_dice: "A pair of white gaming dice cubes with black dots showing six and five",
  toy_ship: "A wooden toy sailing boat with white canvas sail floating in water",
  toy_balloon: "A bunch of colorful shiny helium balloons floating with curly ribbons",
  toy_pyramid: "A classic wooden rainbow stacking ring pyramid toy with ball on top",
  toy_whistle: "A traditional clay carved bird whistle figurine",
  toy_bubbles: "A wand blowing translucent iridescent floating soap bubbles",
  toy_sandbox: "A wooden sandbox filled with golden sand, plastic bucket, and spade",
  toy_watergun: "A bright neon green and orange squirt water blaster gun",
  toy_castle: "A miniature toy fortress castle with stone turrets and battlements",

  // Holidays
  hol_newyear: "A sparkling snowy winter scene with lit festive lanterns and gift boxes",
  hol_birthday: "A birthday celebration with colorful party hat, balloons, and wrapped gift",
  hol_wedding: "A traditional Caucasian wedding celebration with ribbons, car procession, and joy",
  hol_eid: "Eid Mubarak celebration: glowing crescent moon, dates bowl, and elegant teapot",
  hol_kurban: "Eid al-Adha: a sweet friendly fluffy sheep with crescent moon and flowers",
  hol_victory: "Victory day celebration with orange-black ribbon, carnation flowers, and salute",
  hol_constitution: "An official embossed state emblem book with ribbon bookmark",
  hol_gift: "A beautifully wrapped gift box with silk satin ribbon bow and tag",
  hol_balloon: "A giant shiny golden star foil balloon floating with confetti",
  hol_cake: "A delicious multi-layer birthday celebration cake decorated with berries",
  hol_candle: "A warm glowing beeswax candle in an ornate bronze candlestick",
  hol_fireworks: "Vibrant colorful festive fireworks bursts lighting up the dark sky",
  hol_music: "Traditional Caucasian wooden folk instruments with floating musical notes",
  hol_dance: "Traditional Caucasian dancers in silhouette dancing energetic Lezginka",
  hol_celebrate: "Party celebration with burst of colorful confetti, streamers, and sparkles",
  hol_congratulate: "Two cheerful friends warmly embracing and congratulating with smiles",
  hol_table: "A grand festive banquet dining table laden with traditional Caucasian dishes",
  hol_joy: "A group of joyful children laughing and throwing colorful confetti in the air",
  hol_card: "An elegant floral greeting card with handwritten heartfelt calligraphy",
  hol_bouquet: "A magnificent fresh bouquet of blooming red roses and white lilies in paper",
  hol_ribbon: "A long flowing shiny red satin celebration ribbon bow",
  hol_applause: "Hands clapping in enthusiastic warm applause with sparkles",
  hol_chechen_dance: "Authentic Chechen national Lezginka dance with male dancer in papakha and female dancer in silk",
  hol_blessing: "Respectful hands raised together in Dua blessing prayer with gentle golden aura"
};

fs.writeFileSync('scripts/card_prompts.json', JSON.stringify(PROMPTS, null, 2), 'utf8');
console.log('Saved', Object.keys(PROMPTS).length, 'curated prompts to scripts/card_prompts.json');
